### ISSUE TITLE
Unable to expand neosnippet snippets with ncm2

### ISSUE THREAD

**Issue by anelson** [ncm2/ncm2-neosnippet#1]
Hi:
I'm switching over to ncm2 from Deoplete mostly for the better integration of LSP snippets with regular snippets.  I've been using neosnippet for a while now and haven't had any problems before.

I've run into a basic problem which prevents me from using snippets with ncm2.  Here are the details:

# Environment

OS: `Linux microcornelius 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux`

Vim version: 
```
NVIM v0.3.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```
`.vimrc`: https://gist.github.com/anelson/63cd090e80944713b935e84543dfec38

# Steps to Reproduce

* Launch (neo)vim in a Rust project directory
* Edit a Rust source code file
* Start writing a new Rust function by typing `fn` at the end of the file
* ncm2 auto-complete menu will appear.  Press <kbd>C-n</kbd> to select the first option which is also called `fn`.  This is a neosnippet snippet which will expand into a Rust function definition.
* Press <kbd>C-j</kbd> to expand this snippet.

# Expected Behavior

The `fn` snippet expands into a Rust function definition with the cursor on the first placeholder.

# Observed Behavior

The snippet is not expanded, and Vim returns to Normal mode.

# Notes

If after this happens I press <kbd>A</kbd> to append to the end of the line containing `fn`, then press <kbd>C-y</kbd> to dismiss the ncm2 autocomplete popup, and _then_ press <kbd>C-k</kbd> then the snippet expansion happens as normal.  

I'm really eager to swtich over to the better LSP functionality in ncm2 but this snippet issue is getting in the way.  I'd appreciate any help.

**Comment by af** [comment]
I have the same issue. Snippets show up in the autocomplete as expected, but selecting the autocomplete menu item doesn't expand the snippet. The snippet's name is left behind and the completion menu is closed.

FWIW I'm using the inoremap line from the README in my vimrc:
```inoremap <silent> <expr> <CR> ncm2_neosnippet#expand_or("\<CR>", 'n')```

neovim 0.3.3, iTerm2, tmux, macOS

**Comment by roxma** [comment]
Please test the latest version

**Comment by af** [comment]
Works for me now, thank you!

**Comment by anelson** [comment]
Confirmed works for me also, thanks for the quick fix!
